# Generated by Django 5.1.6 on 2026-05-01 04:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0054_iglesia_categoria_iglesia_iglesia_padre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
            ],
        ),
        migrations.CreateModel(
            name='CursoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre_grupo', models.CharField(max_length=50)),
                ('aula', models.CharField(max_length=50)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora', models.TimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.curso')),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
                ('maestro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad_maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.cursoperiodo')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado')], default='activo', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('curso_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.cursoperiodo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.clase')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuela.especialidad_maestro')),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escuela.clase')),
                ('curso_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.cursoperiodo')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuela.maestro')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='maestro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuela.maestro'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('url_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('valido', models.BooleanField(default=True)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escuela.inscripcion')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuela.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('validada', models.BooleanField(default=False)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.evaluacion')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.inscripcion')),
                ('calificada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuela.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
                ('nivel_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escuela.nivel')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.nivel'),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
            ],
        ),
        migrations.AddField(
            model_name='cursoperiodo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.periodo'),
        ),
        migrations.CreateModel(
            name='PreguntaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('escala', 'Escala 1-5'), ('texto', 'Respuesta abierta')], max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.evaluacioncurso')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.inscripcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.preguntaevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales/')),
                ('url', models.URLField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.tema')),
            ],
        ),
        migrations.CreateModel(
            name='TemaCursoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('curso_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.cursoperiodo')),
                ('maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuela.maestro')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.tema')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCursoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.material')),
                ('tema_curso_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.temacursoperiodo')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.temacursoperiodo'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['curso_periodo'], name='escuela_ins_curso_p_3adf01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('estudiante', 'curso_periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('inscripcion', 'clase')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('inscripcion', 'evaluacion')},
        ),
        migrations.AlterUniqueTogether(
            name='cursoperiodo',
            unique_together={('curso', 'periodo', 'nombre_grupo')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestaevaluacion',
            unique_together={('inscripcion', 'pregunta')},
        ),
    ]
