# Generated by Django 5.1.6 on 2026-05-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_iglesia_categoria_iglesia_iglesia_padre'),
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nivel__orden', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='especialidad_maestro',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='materialcursoperiodo',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='temacursoperiodo',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='materialcursoperiodo',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='periodo',
            name='activo_inscripcion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='temacursoperiodo',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('iglesia', 'nombre', 'nivel')},
        ),
        migrations.AlterUniqueTogether(
            name='especialidad_maestro',
            unique_together={('iglesia', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='materialcursoperiodo',
            unique_together={('tema_curso_periodo', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='nivel',
            unique_together={('iglesia', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('iglesia', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('curso', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='temacursoperiodo',
            unique_together={('curso_periodo', 'tema')},
        ),
    ]
