# Generated by Django 5.1.6 on 2026-06-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='tema_curso_periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escuela.temacursoperiodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='especialidad_maestro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nivel',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.inscripcion')),
                ('tema_curso_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.temacursoperiodo')),
            ],
        ),
    ]
