# Generated by Django 5.1.6 on 2026-06-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_calificacion_tema_curso_periodo_curso_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoperiodo',
            name='cerrar_asistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cursoperiodo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cursoperiodo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursoperiodo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursoperiodo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cursoperiodo',
            name='permitir_autoinscripcion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cursoperiodo',
            name='publicar_calificaciones',
            field=models.BooleanField(default=False),
        ),
    ]
