# Generated by Django 5.1.6 on 2026-06-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_cursoperiodo_cerrar_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='curso_periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escuela.cursoperiodo'),
            preserve_default=False,
        ),
    ]
