# Generated by Django 5.1.6 on 2026-06-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_clase_curso_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='desarrollado',
            field=models.BooleanField(default=False),
        ),
    ]
