# Generated by Django 5.1.6 on 2026-06-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_tema_desarrollado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='desarrollado',
        ),
        migrations.AddField(
            model_name='temacursoperiodo',
            name='desarrollado',
            field=models.BooleanField(default=False),
        ),
    ]
