# Generated by Django 5.1.6 on 2025-02-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_ministerio_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol_ministerio',
            name='codigo',
        ),
    ]
