# Generated by Django 5.1.6 on 2025-02-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_rol_ministerio_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesia',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='pastor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
