# Generated by Django 5.1.6 on 2025-02-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_iglesia_correo_iglesia_direccion_iglesia_pastor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Estado_grupoCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.comuna')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='GrupoCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora', models.TimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.barrio')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.estado_grupocasa')),
                ('id_miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_departamento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.departamento')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.municipio'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_pais',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.pais'),
        ),
    ]
