# Generated by Django 5.1.6 on 2026-04-18 15:47

import django.db.models.deletion
import presbiterio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_organo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_asamblea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Estado_asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_miembro_organo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Estado_mocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Estado_organo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Modalidad_asamblea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion_votacion_mocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion_asamblea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_mocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
                ('umbral_aprobacion', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_organo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_presenta_mocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asamblea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('habilita_votacion', models.BooleanField(default=False)),
                ('finalizada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.estado_asamblea')),
                ('id_modalidad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.modalidad_asamblea')),
                ('id_sesion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.sesion_asamblea')),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.estado_miembro')),
                ('id_usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tipo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.tipo_miembro')),
            ],
            options={
                'ordering': ['id_tipo'],
            },
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_asamblea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.asamblea')),
                ('id_estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.estado_asistente')),
                ('id_miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=200)),
                ('asunto', models.TextField(blank=True, null=True)),
                ('conclusiones', models.TextField(blank=True, null=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('id_miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Organo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
                ('funcion', models.TextField(blank=True, null=True)),
                ('presenta_mocion', models.BooleanField(default=False)),
                ('elegible_asamblea', models.BooleanField(default=False)),
                ('cantidad_miembros', models.PositiveIntegerField(null=True)),
                ('cantidad_ministro', models.PositiveIntegerField(null=True)),
                ('estado_postulacion', models.PositiveIntegerField(default=0, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.estado_organo')),
                ('id_tipo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.tipo_organo')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro_organo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.cargo_organo')),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.estado_miembro_organo')),
                ('id_miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.miembro')),
                ('id_organo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.organo')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=presbiterio.models.acta_upload_path)),
                ('principal', models.BooleanField(default=False)),
                ('id_acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='presbiterio.acta')),
                ('id_organo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.organo')),
            ],
        ),
        migrations.AddField(
            model_name='acta',
            name='id_organo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.organo'),
        ),
        migrations.CreateModel(
            name='Postulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votos', models.PositiveIntegerField(default=0, null=True)),
                ('elegido', models.BooleanField(default=False, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_asamblea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.asamblea')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.cargo_organo')),
                ('id_miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.miembro')),
                ('id_organo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulados', to='presbiterio.organo')),
            ],
        ),
        migrations.CreateModel(
            name='Mocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mocion', models.TextField(blank=True, null=True)),
                ('encurso', models.BooleanField(default=False)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('afavor', models.PositiveIntegerField(null=True)),
                ('encontra', models.PositiveIntegerField(null=True)),
                ('enblanco', models.PositiveIntegerField(null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_asamblea', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.asamblea')),
                ('id_asistente_presenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.asistente')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.estado_mocion')),
                ('id_organo_presenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.organo')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.tipo_mocion')),
                ('id_tipo_presenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.tipo_presenta_mocion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Votacion_mocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_asamblea', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.asamblea')),
                ('id_asistente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.asistente')),
                ('id_mocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.mocion')),
                ('id_opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.opcion_votacion_mocion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VotacionPostulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('conteo_final', models.PositiveIntegerField(blank=True, null=True)),
                ('id_asamblea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.asamblea')),
                ('id_postulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.postulado')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
