# Generated by Django 5.1.6 on 2026-04-21 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_configuracioniglesia_dias_deshab_servicio'),
        ('presbiterio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presbiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiPresbiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('fecha_reporte', models.DateField()),
                ('presbiterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.presbiterio')),
            ],
            options={
                'unique_together': {('presbiterio', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='ReporteAnualIglesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('miembros_inicio', models.IntegerField(default=0)),
                ('miembros_ganados', models.IntegerField(default=0)),
                ('miembros_perdidos', models.IntegerField(default=0)),
                ('miembros_final', models.IntegerField(default=0)),
                ('miembros_activos', models.IntegerField(default=0)),
                ('promedio_escuela', models.IntegerField(default=0)),
                ('diezmos_ofrendas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aportes_presbiterio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
            ],
            options={
                'unique_together': {('iglesia', 'anio')},
            },
        ),
    ]
