# Generated by Django 5.1.6 on 2026-04-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presbiterio', '0002_presbiterio_confipresbiterio_reporteanualiglesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='confipresbiterio',
            name='cantidad_anios',
            field=models.IntegerField(default=3),
        ),
    ]
