# Generated by Django 5.1.6 on 2026-04-22 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presbiterio', '0003_confipresbiterio_cantidad_anios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_presbiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100, null=True)),
                ('superusuario', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('presbiterio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.presbiterio')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['presbiterio'],
            },
        ),
    ]
