# Generated by Django 5.1.6 on 2026-04-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presbiterio', '0004_usuario_presbiterio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confipresbiterio',
            options={'ordering': ['presbiterio']},
        ),
        migrations.AlterUniqueTogether(
            name='confipresbiterio',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='confipresbiterio',
            name='anio',
        ),
    ]
