# Generated by Django 5.1.6 on 2026-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presbiterio', '0005_alter_confipresbiterio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_presbiterio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
