# Generated by Django 5.1.6 on 2026-06-29 06:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presbiterio', '0006_usuario_presbiterio_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presbiterio',
            options={'ordering': ['nombre'], 'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AddField(
            model_name='asamblea',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='presbiterio',
            name='codigo',
            field=models.CharField(default=1, editable=False, max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presbiterio',
            name='organizacion_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='presbiterio.presbiterio'),
        ),
        migrations.AddField(
            model_name='presbiterio',
            name='tipo',
            field=models.CharField(choices=[('G', 'General'), ('S', 'Sínodo'), ('P', 'Presbiterio')], db_index=True, default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='presbiterio',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
