# Generated by Django 5.1.6 on 2026-06-29 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presbiterio', '0007_alter_presbiterio_options_asamblea_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asamblea',
            name='organizacion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='asambleas', to='presbiterio.presbiterio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='organizacion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='presbiterio.presbiterio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organo',
            name='organizacion',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_organo', to='presbiterio.presbiterio'),
            preserve_default=False,
        ),
    ]
