# Generated by Django 5.1.6 on 2026-06-29 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presbiterio', '0008_asamblea_organizacion_miembro_organizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_organo',
            name='organizacion',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_organo', to='presbiterio.presbiterio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organo',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organos', to='presbiterio.presbiterio'),
        ),
    ]
