# Generated by Django 5.1.6 on 2025-02-14 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2)),
                ('apellido', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuario_iglesia',
            name='superusuario',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=200)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Rol_ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=200)),
                ('id_ministerio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.ministerio')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro_ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_miembro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.miembro')),
                ('id_ministerio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.ministerio')),
                ('id_rol_ministerio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.rol_ministerio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=2)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.categoria_servicio')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Participante_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_miembro_ministerio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.miembro_ministerio')),
                ('id_servicio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.servicio')),
            ],
        ),
    ]
