# Generated by Django 5.1.6 on 2025-02-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_miembro_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='celular',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
