# Generated by Django 5.1.6 on 2025-02-14 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_miembro_celular_alter_miembro_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_miembro_ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.miembro_ministerio')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.servicio')),
            ],
        ),
        migrations.DeleteModel(
            name='Participante_servicio',
        ),
    ]
