# Generated by Django 5.1.6 on 2025-02-14 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_participanteservicio_delete_participante_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_servicio',
            name='id_iglesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.iglesia'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_iglesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.iglesia'),
        ),
    ]
