# Generated by Django 5.1.6 on 2025-02-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_rol_ministerio_id_ministerio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministerio',
            name='codigo',
        ),
    ]
