# Generated by Django 5.1.6 on 2025-02-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_comuna_departamento_estado_grupocasa_pais_barrio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='observacion',
        ),
        migrations.AddField(
            model_name='pais',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
