# Generated by Django 5.1.6 on 2025-07-11 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_pais_observacion_pais_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteservicio',
            name='id_rol_ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.rol_ministerio'),
        ),
    ]
