# Generated by Django 5.1.6 on 2026-03-28 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_participanteservicio_id_rol_ministerio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBienvenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
            ],
        ),
        migrations.CreateModel(
            name='Bienvenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefonico', models.CharField(blank=True, max_length=30, null=True)),
                ('texto_biblico', models.TextField(blank=True, null=True)),
                ('link_playlist', models.CharField(blank=True, max_length=500, null=True)),
                ('link_devocional_youversion', models.CharField(blank=True, max_length=500, null=True)),
                ('link_libro_online', models.CharField(blank=True, max_length=500, null=True)),
                ('link_video_bienvenida', models.CharField(blank=True, max_length=500, null=True)),
                ('mensaje_bienvenida', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_tipo_bienvenida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.tipobienvenida')),
            ],
        ),
    ]
