# Generated by Django 5.1.6 on 2026-04-03 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_tipobienvenida_bienvenida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
            ],
        ),
        migrations.CreateModel(
            name='Consolidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('nombre_invito', models.CharField(blank=True, max_length=150)),
                ('celular_invito', models.CharField(blank=True, max_length=20)),
                ('grupo_casa', models.CharField(blank=True, max_length=150)),
                ('observacion', models.TextField(blank=True)),
                ('en_seguimiento', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.categoria_servicio')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.miembro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.red')),
            ],
        ),
    ]
