# Generated by Django 5.1.6 on 2026-04-04 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_red_consolidacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidacion',
            name='celular_invito',
        ),
        migrations.AlterField(
            model_name='consolidacion',
            name='grupo_casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.grupocasa'),
        ),
        migrations.AlterField(
            model_name='consolidacion',
            name='nombre_invito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invito', to='base.miembro'),
        ),
    ]
