# Generated by Django 5.1.6 on 2026-04-04 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_consolidacion_celular_invito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocasa',
            name='iglesia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.iglesia'),
            preserve_default=False,
        ),
    ]
