# Generated by Django 5.1.6 on 2026-04-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_grupocasa_iglesia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidacion',
            name='en_seguimiento',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En proceso'), ('T', 'Terminado')], default='P', max_length=1),
        ),
    ]
