# Generated by Django 5.1.6 on 2026-04-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_consolidacion_en_seguimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consolidacion',
            old_name='en_seguimiento',
            new_name='en_seguimientoa',
        ),
    ]
