# Generated by Django 5.1.6 on 2026-04-05 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_en_seguimientoa_consolidacion_en_seguimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIglesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_alerta_con_1', models.IntegerField(default=3, verbose_name='Días alerta nivel 1')),
                ('dias_alerta_con_2', models.IntegerField(default=5, verbose_name='Días alerta nivel 2')),
                ('iglesia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
            ],
        ),
    ]
