# Generated by Django 5.1.6 on 2026-04-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_configuracioniglesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocasa',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='red',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
