# Generated by Django 5.1.6 on 2026-04-07 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_grupocasa_id_usuario_ministerio_red'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistentesGrupoCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('C', 'Consolidación'), ('A', 'Asistente'), ('U', 'Ausente')], default='C', max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('consolidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.consolidacion')),
                ('grupo_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.grupocasa')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='AsistentesRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('C', 'Consolidación'), ('A', 'Asistente'), ('U', 'Ausente')], default='C', max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('consolidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.consolidacion')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.miembro')),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.red')),
            ],
        ),
    ]
