# Generated by Django 5.1.6 on 2026-04-08 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_asistentesgrupocasa_asistentesred'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolEquipoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='EquipoGrupoCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('grupo_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.grupocasa')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.miembro')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.rolequipogrupo')),
            ],
        ),
        migrations.AddField(
            model_name='asistentesgrupocasa',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.equipogrupocasa'),
        ),
    ]
