# Generated by Django 5.1.6 on 2026-04-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rolequipogrupo_equipogrupocasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='lider',
            field=models.BooleanField(default=False),
        ),
    ]
