# Generated by Django 5.1.6 on 2026-04-08 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_miembro_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolequipogrupo',
            name='iglesia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.iglesia'),
            preserve_default=False,
        ),
    ]
