# Generated by Django 5.1.6 on 2026-04-08 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rolequipogrupo_iglesia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolequipogrupo',
            name='iglesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.iglesia'),
        ),
    ]
