# Generated by Django 5.1.6 on 2026-04-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_rolequipogrupo_iglesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentesgrupocasa',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
