# Generated by Django 5.1.6 on 2026-04-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_asistentesgrupocasa_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentesred',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asistentesgrupocasa',
            name='estado',
            field=models.CharField(choices=[('C', 'Consolidación'), ('S', 'Seguimiento'), ('A', 'Asistente'), ('U', 'Ausente')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='asistentesred',
            name='estado',
            field=models.CharField(choices=[('C', 'Consolidación'), ('S', 'Seguimiento'), ('A', 'Asistente'), ('U', 'Ausente')], default='C', max_length=1),
        ),
    ]
