# Generated by Django 5.1.6 on 2026-04-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_asistentesred_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistentesred',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
