# Generated by Django 5.1.6 on 2026-04-10 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_asistentesred_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentesred',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.miembro_ministerio'),
        ),
    ]
