# Generated by Django 5.1.6 on 2026-04-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_asistentesred_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidacion',
            name='termina_seguimiento',
            field=models.CharField(choices=[('G', 'Grupo en casa'), ('R', 'Red')], default='R', max_length=1),
            preserve_default=False,
        ),
    ]
