# Generated by Django 5.1.6 on 2026-04-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_consolidacion_termina_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidacion',
            name='termina_seguimiento',
            field=models.CharField(choices=[('G', 'Grupo en casa'), ('R', 'Red'), ('C', 'Consolidacion'), ('N', 'Ninguno')], default='C', max_length=1),
        ),
    ]
