# Generated by Django 5.1.6 on 2026-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_servicioministerio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
