# Generated by Django 5.1.6 on 2026-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_servicio_hora_fin_servicio_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_iglesia',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
