# Generated by Django 5.1.6 on 2026-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_usuario_iglesia_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerio',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
