# Generated by Django 5.1.6 on 2026-04-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_ministerio_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerio',
            name='codigo',
            field=models.CharField(default='CC', max_length=2),
            preserve_default=False,
        ),
    ]
