# Generated by Django 5.1.6 on 2026-04-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_ministerio_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioniglesia',
            name='mensaje_bienvenida_whatsapp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consolidacion',
            name='fecha_whatsapp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consolidacion',
            name='whatsapp_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
