# Generated by Django 5.1.6 on 2026-04-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_configuracioniglesia_mensaje_bienvenida_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='celular',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
