# Generated by Django 5.1.6 on 2026-04-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_miembro_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioniglesia',
            name='link_bienvenida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioniglesia',
            name='mensaje_linkbienvenida_whatsapp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
