# Generated by Django 5.1.6 on 2026-04-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_configuracioniglesia_link_bienvenida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='red',
            name='codigo',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipobienvenida',
            name='red',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.red'),
            preserve_default=False,
        ),
    ]
