# Generated by Django 5.1.6 on 2026-04-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_red_codigo_tipobienvenida_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioniglesia',
            name='dias_deshab_servicio',
            field=models.IntegerField(default=5, verbose_name='Días eliminar servicio'),
        ),
    ]
