# Generated by Django 5.1.6 on 2026-04-22 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_configuracioniglesia_dias_deshab_servicio'),
        ('presbiterio', '0003_confipresbiterio_cantidad_anios'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesia',
            name='presbiterio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='presbiterio.presbiterio'),
            preserve_default=False,
        ),
    ]
