# Generated by Django 5.1.6 on 2026-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_iglesia_presbiterio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienvenida',
            name='horario_general',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bienvenida',
            name='horario_general_min',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bienvenida',
            name='infromacion_general',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bienvenida',
            name='infromacion_general_min',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
