# Generated by Django 5.1.6 on 2026-04-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_bienvenida_horario_general_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bienvenida',
            old_name='infromacion_general',
            new_name='informacion_general',
        ),
        migrations.RenameField(
            model_name='bienvenida',
            old_name='infromacion_general_min',
            new_name='informacion_general_min',
        ),
    ]
