# Generated by Django 5.1.6 on 2026-04-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_rename_infromacion_general_bienvenida_informacion_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienvenida',
            name='horario_general',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bienvenida',
            name='horario_general_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bienvenida',
            name='informacion_general',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bienvenida',
            name='informacion_general_min',
            field=models.TextField(blank=True, null=True),
        ),
    ]
