# Generated by Django 5.1.6 on 2026-04-29 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_bienvenida_horario_general_and_more'),
        ('presbiterio', '0005_alter_confipresbiterio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_iglesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('presbiterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presbiterio.presbiterio')),
            ],
        ),
    ]
