# Generated by Django 5.1.6 on 2026-04-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_categoria_iglesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesia',
            name='categoria',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='base.categoria_iglesia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iglesia',
            name='iglesia_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijas', to='base.iglesia'),
        ),
    ]
