# Generated by Django 5.1.6 on 2026-05-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_evento_eventodia_eventoprogramado_rangoedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
