# Generated by Django 5.1.6 on 2026-05-04 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_evento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoprogramado',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('cerrado', 'Cerrado')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='eventoprogramado',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoprogramado',
            name='iglesia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.iglesia'),
            preserve_default=False,
        ),
    ]
