# Generated by Django 5.1.6 on 2026-05-04 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_eventoprogramado_estado_eventoprogramado_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionevento',
            name='evento_programado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.eventoprogramado'),
        ),
    ]
