# Generated by Django 5.1.6 on 2026-05-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_inscripcionevento_evento_programado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcionevento',
            unique_together={('evento_programado', 'miembro')},
        ),
        migrations.RemoveField(
            model_name='inscripcionevento',
            name='evento',
        ),
    ]
