# Generated by Django 5.1.6 on 2026-05-04 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_inscripcionevento_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionevento',
            name='rango_edad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.rangoedad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rangoedad',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.red'),
        ),
    ]
