# Generated by Django 5.1.6 on 2026-05-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_inscripcionevento_rango_edad_rangoedad_red'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistenciaevento',
            old_name='fecha_registro',
            new_name='fecha_checkin',
        ),
    ]
