# Generated by Django 5.1.6 on 2026-05-07 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_rename_fecha_registro_asistenciaevento_fecha_checkin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupocasa',
            name='id_miembro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.miembro'),
        ),
        migrations.AlterUniqueTogether(
            name='ministerio',
            unique_together={('codigo', 'id_usuario')},
        ),
    ]
