# Generated by Django 5.1.6 on 2026-05-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_grupocasa_id_miembro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='identificacion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
