# Generated by Django 5.1.6 on 2026-05-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_alter_miembro_identificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=200)),
                ('id_iglesia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
            ],
            options={
                'ordering': ['codigo'],
                'unique_together': {('codigo', 'id_iglesia')},
            },
        ),
        migrations.AddField(
            model_name='miembro',
            name='categoria_lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categoria_lider'),
        ),
    ]
