# Generated by Django 5.1.6 on 2026-05-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_categoria_lider_miembro_categoria_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_lider',
            name='id_iglesia',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='base.iglesia'),
            preserve_default=False,
        ),
    ]
