# Generated by Django 5.1.6 on 2026-05-07 19:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_alter_categoria_lider_id_iglesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesia',
            name='token_registro',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
