# Generated by Django 5.1.6 on 2026-05-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_alter_iglesia_token_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='ocupacion_actual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='ocupacion_interesada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='preparacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
