# Generated by Django 5.1.6 on 2026-05-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_citaconsolidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaconsolidacion',
            name='estado',
            field=models.CharField(choices=[('A', 'Agendada'), ('T', 'Atendida'), ('C', 'Cancelada')], default='A', max_length=1),
        ),
    ]
