# Generated by Django 5.1.6 on 2026-05-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_citaconsolidacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaconsolidacion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
