# Generated by Django 5.1.6 on 2026-05-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_alter_citaconsolidacion_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioniglesia',
            name='mensaje_whatsapp_cita',
            field=models.TextField(blank=True, null=True),
        ),
    ]
