# Generated by Django 5.1.6 on 2026-05-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_configuracioniglesia_mensaje_whatsapp_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_iglesia',
            name='consolidador',
            field=models.BooleanField(default=False),
        ),
    ]
