# Generated by Django 5.1.6 on 2026-05-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_usuario_iglesia_consolidador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario_iglesia',
            old_name='consolidador',
            new_name='rol_consolidador',
        ),
    ]
