# Generated by Django 5.1.6 on 2026-05-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_rename_consolidador_usuario_iglesia_rol_consolidador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistenciaevento',
            old_name='es_visitante',
            new_name='es_miembro',
        ),
    ]
