# Generated by Django 5.1.6 on 2026-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_rename_es_visitante_asistenciaevento_es_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionevento',
            name='otra_congregacion',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
