# Generated by Django 5.1.6 on 2026-05-09 19:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_inscripcionevento_otra_congregacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoprogramado',
            name='token_registro',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
