# Generated by Django 5.1.6 on 2026-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_eventoprogramado_token_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoprogramado',
            name='edad_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoprogramado',
            name='edad_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoprogramado',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
