# Generated by Django 5.1.6 on 2026-05-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_eventoprogramado_edad_max_eventoprogramado_edad_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangoedad',
            name='edad_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rangoedad',
            name='edad_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
