# Generated by Django 5.1.6 on 2026-05-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_alter_rangoedad_edad_max_alter_rangoedad_edad_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesia',
            name='codigo',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
