# Generated by Django 5.1.6 on 2026-05-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_iglesia_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iglesia',
            name='codigo',
            field=models.CharField(default=1, editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
