# Generated by Django 5.1.6 on 2026-05-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_alter_iglesia_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iglesia',
            name='codigo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
