# Generated by Django 5.1.6 on 2026-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_alter_iglesia_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienvenida',
            name='nada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
