# Generated by Django 5.1.6 on 2026-05-13 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_alter_iglesia_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienvenida',
            name='token_registro',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
