# Generated by Django 5.1.6 on 2026-05-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_bienvenida_nada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipobienvenida',
            options={'ordering': ['codigo']},
        ),
        migrations.AddField(
            model_name='tipobienvenida',
            name='codigo',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
