# Generated by Django 5.1.6 on 2026-05-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_alter_tipobienvenida_options_tipobienvenida_codigo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipobienvenida',
            unique_together={('codigo', 'id_iglesia')},
        ),
    ]
