# Generated by Django 5.1.6 on 2026-05-13 03:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_alter_bienvenida_token_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienvenida',
            name='token_registro',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
