# Generated by Django 5.1.6 on 2026-05-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_alter_tipobienvenida_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoprogramado',
            name='codigo',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
