# Generated by Django 5.1.6 on 2026-05-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_alter_bienvenida_token_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienvenida',
            name='token_registro',
        ),
    ]
