# Generated by Django 5.1.6 on 2026-05-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_eventoprogramado_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoprogramado',
            name='codigo',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
