# Generated by Django 5.1.6 on 2026-05-13 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_remove_bienvenida_token_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienvenida',
            name='token_registro',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
