# Generated by Django 5.1.6 on 2026-05-15 17:14

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_alter_eventoprogramado_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoprogramado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.ruta_imagen_evento),
        ),
    ]
