# Generated by Django 5.1.6 on 2026-05-16 13:01

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_eventoprogramado_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioniglesia',
            name='imagen_registro_miembro',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.ruta_imagen_registro_miembro),
        ),
    ]
