# Generated by Django 5.1.6 on 2026-05-18 21:05

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_configuracioniglesia_imagen_registro_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioniglesia',
            name='imagen_banner_iglesia',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.ruta_imagen_banner_iglesia),
        ),
    ]
