# Generated by Django 5.1.6 on 2026-05-18 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_configuracioniglesia_imagen_banner_iglesia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_iglesia',
            name='id_iglesia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_iglesia', to='base.iglesia'),
        ),
    ]
