# Generated by Django 5.1.6 on 2026-05-22 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0092_alter_usuario_iglesia_id_iglesia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroConsolidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.iglesia')),
            ],
        ),
        migrations.AlterField(
            model_name='consolidacion',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.miembroconsolidacion'),
        ),
    ]
