# Generated by Django 5.1.6 on 2026-05-23 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_miembroconsolidacion_alter_consolidacion_miembro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaconsolidacion',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.miembroconsolidacion'),
        ),
    ]
