# Generated by Django 5.1.6 on 2026-05-24 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_alter_citaconsolidacion_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentesgrupocasa',
            name='miembroConsolidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.miembroconsolidacion'),
        ),
        migrations.AddField(
            model_name='asistentesred',
            name='miembroConsolidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.miembroconsolidacion'),
        ),
    ]
