# Generated by Django 5.1.6 on 2026-05-24 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_asistentesgrupocasa_miembroconsolidacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistentesgrupocasa',
            name='miembroConsolidacion',
        ),
        migrations.RemoveField(
            model_name='asistentesred',
            name='miembroConsolidacion',
        ),
        migrations.CreateModel(
            name='AsistentesGrupoCasaConsolidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('C', 'Consolidación'), ('S', 'Seguimiento'), ('A', 'Asistente'), ('U', 'Ausente')], default='C', max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('consolidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.consolidacion')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.equipogrupocasa')),
                ('grupo_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.grupocasa')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.miembroconsolidacion')),
            ],
        ),
        migrations.CreateModel(
            name='AsistentesRedConsolidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('C', 'Consolidación'), ('S', 'Seguimiento'), ('A', 'Asistente'), ('U', 'Ausente')], default='C', max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('consolidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.consolidacion')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.miembro_ministerio')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.miembroconsolidacion')),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.red')),
            ],
        ),
    ]
