# Generated by Django 5.1.6 on 2026-05-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_remove_asistentesgrupocasa_miembroconsolidacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoprogramado',
            name='msg_registro_exitoso',
            field=models.TextField(blank=True, default='Registro exitoso', verbose_name='Mensaje registro exitoso'),
        ),
    ]
