# Generated by Django 5.1.6 on 2026-05-27 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_eventoprogramado_msg_registro_exitoso'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoprogramado',
            name='solicitar_rango_edad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='val_rango_edad',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inscripcionevento',
            name='rango_edad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.rangoedad'),
        ),
    ]
