# Generated by Django 5.1.6 on 2026-06-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_eventoprogramado_solicitar_rango_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidacion',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
