# Generated by Django 5.1.6 on 2026-06-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_consolidacion_fecha_terminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienvenida',
            name='link_playlist_spotify',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
